# Generated by Django 4.1.3 on 2022-11-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            name='post_foto_video_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personneloptions',
            name='personnel_options',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personnel_options', serialize=False, to='personnel.consentform'),
        ),
    ]
