# Generated by Django 4.1.3 on 2022-11-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personneloptions_post_foto_video_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personneloptions',
            old_name='post_foto_video_audio',
            new_name='post_photo_video_audio',
        ),
    ]
