# Generated by Django 4.1.3 on 2022-11-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_rename_post_foto_video_audio_personneloptions_post_photo_video_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneloptions',
            name='voluntary_activity',
            field=models.BooleanField(default=False),
        ),
    ]
