# Generated by Django 4.1.3 on 2022-11-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_personneloptions_corporate_assets'),
    ]

    operations = [
        migrations.CreateModel(
            model_name='personneloptions',
            name='Issubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
