# Generated by Django 4.1.3 on 2022-11-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_issubmitted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issubmitted',
        ),
        migrations.AddField(
            model_name='personneloptions',
            name='discount_card',
            field=models.BooleanField(default=False),
        ),
    ]
