# Generated by Django 4.1.3 on 2022-11-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_delete_issubmitted_personneloptions_discount_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Is_submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='consentform',
            name='is_submitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.is_submitted'),
        ),
    ]
