# Generated by Django 4.1.3 on 2022-11-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_is_submitted_alter_consentform_is_submitted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Is_submitted',
            new_name='Issubmitted',
        ),
    ]
